services:
  smsweb:
    image: ccr.ccs.tencentyun.com/other_biz/smsweb:latest
    container_name: smsweb
    restart: on-failure:3
    ports:
      - "9000:9000"
    environment:
      # Application Configuration
      - NODE_ENV=production
    volumes:
      - smsweb_data:/app/data
    network_mode: bridge

volumes:
  smsweb_data:
    name: smsweb_data
